<?php
   print_r($productData);
?>

<p>增加商品</p>
<form action="product/add" method=POST>
   <input name="product_name" type="text" placeholder="product_name">
   <input name="money" type="text" placeholder="money">
   <input name="amount" type="text" placeholder="amount">
   <input name="money_type" type="text" placeholder="money_type">
   <input name="category_id" type="text" placeholder="category">
   <input type="submit" value="add">
</form>

<p>修改商品</p>
<form action="product/edit" method=POST>
   <input name="product_name" type="text" placeholder="product_name">
   <input name="money" type="text" placeholder="money">
   <input name="amount" type="text" placeholder="amount">
   <input name="money_type" type="text" placeholder="money_type">
   <input name="category_id" type="text" placeholder="category">
   <input type="submit" value="change">
</form>

<p>删除商品</p>
<form action="product/del" method=POST>
   <input name="product_name" type="text" placeholder="product_name">
   <input type="submit" value="delete">
</form>

<p>查找商品</p>
<form action="product/get" method=GET>
   <input name="product_name" type="text" placeholder="product_name">
   <input type="submit" value="get">
</form>
