<?php //require "admin.html";?>
<ul class="breadcrumb">
   <li><a href="/admin">管理员设置</a> <span class="divider">/</span></li>
   <li class="active">添加管理员</li>
</ul>

<div class="container-fluid">
   <div class="row-fluid">
      <div class="row-fluid">

         <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>提示:</strong> 请谨慎操作
         </div>

         <div class="block">
            <form action="" method=POST>
               <input name="username" type="text" placeholder="username">
               <input name="password" type="password" placeholder="password">
               <input name="repassword" type="password" placeholder="repassword">
               <input name="email" type="text" placeholder="email">
               <input type="submit" class="btn btn-primary " value="add">
            </form>
         </div>
      </div>
   </div>
</div>

