<?php //require "admin.html";?>
<ul class="breadcrumb">
   <li><a href="">主页</a> <span class="divider">/</span></li>
   <li class="active">欢迎页</li>
</ul>

<div class="container-fluid">
   <div class="row-fluid">


      <div class="row-fluid">

         <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>提示:</strong> 请谨慎操作
         </div>

         <div class="block">

            <p>登陆</p>
            <form action="admin/login" method=POST>
               <input name="username" type="text" placeholder="username">
               <input name="password" type="password" placeholder="password">
               <input name="submit" class="btn btn-primary " type="submit" class="btn btn-primary " value="login">
            </form>

            <!--
            <p>修改用户</p>
            <form action="admin/edit" method=POST>
               <input name="username" type="text" placeholder="username" value="admin">
               <input name="password" type="password" placeholder="password" value="123456789">
               <input name="repassword" type="password" placeholder="repassword" value="123456789">
               <input name="email" type="text" placeholder="email" value="yantze@111.com">
               <input name="submit" class="btn btn-primary " type="submit" class="btn btn-primary " value="change">
            </form>
            -->

            <p>删除用户</p>
            <form action="admin/del" method=POST>
               <input name="username" type="text" placeholder="username" value="admin">
               <input name="password" type="password" placeholder="password" value="123456789">
               <input name="submit" class="btn btn-primary " type="submit" class="btn btn-primary " value="delete">
            </form>

         </div>
      </div>
   </div>
</div>

